[project]
name = "rag-chatbot"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "pymupdf",
    "langchain",
    "langchain-community",
    "langchain-openai",
    "langchain-text-splitters",
    "langchain-weaviate",
    "weaviate-client",
    "python-dotenv>=1.0.1",
    "fastapi",
    "uvicorn[standard]",
    "simsimd"
]

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]